### ISSUE TITLE
PHP7 - All instances of mt_rand() should be changed to random_int();

### ISSUE THREAD

**Issue by wmelton** [gburtini/Probability-Distributions-for-PHP#15]
According to the PHP7 documentation, a new function `random_int();` has been introduced in PHP7 that is more cryptographically appropriate as well as a more 'truly' random number.

The new documentation has the following to say, 

> Generates cryptographic random integers that are suitable for use where unbiased results are critical, such as when shuffling a deck of cards for a poker game.

Accordingly, the documentation for `mt_rand();` has been updated with the release of 7.0 to say the following: 

> Caution: This function does not generate cryptographically secure values, and should not be used for cryptographic purposes. If you need a cryptographically secure value, consider using random_int(), random_bytes(), or openssl_random_pseudo_bytes() instead.

PHP.net docs - [http://php.net/manual/en/function.random-int.php](http://php.net/manual/en/function.random-int.php)

**Comment by gburtini** [comment]
I would be happy to promote the usage of the new `random_` methods once they are inside our expected support window. I intend to deprecate the 5.x series soon for this project, but I don't want to remove backwards compatibility solely for the sake of breaking things.

Importantly, however, this is **not** a cryptographic library. That said, the cryptographic tests of randomness might have some interesting value in terms of what we mean by, say, "drawing from a uniform distribution." If there were a case to be made for this today, I would be willing to put a `function_exists` or userland polyfill style implementation in place.

**Comment by wmelton** [comment]
Exactly - while definitely not a cryptographic library, it would seem that the 'true' randomness of a distribution is important when being used for A/B testing or optimizations. If PHP documentation is correct, `random_int()` "should" produce a more truly reliable, mathematically correct result.

**Comment by gburtini** [comment]
This fundamentally comes down to what it means to be "truly" random. A question I've struggled with for a long time and is probably outside the scope of this chat. There are, however, a number of tests used to define _true_ randomness. 

I believe we should meet all the tests that would matter for that use case using Mersenne Twister, but it would be worth eventually adding unit tests to this library that ensure that is the case, to the extent they are meaningful.

For example, the [Diehard tests](https://en.wikipedia.org/wiki/Diehard_tests) or [TestU01](http://www.iro.umontreal.ca/~simardr/testu01/tu01.html). I am not particularly familiar with the cryptographic randomness test suites, but the non-cryptographic properties should be sufficient with respect to A/B testing or any of the other common applications of these distributions like memoryless cache expiration or Monte Carlo simulations. Cryptographic tests aim to understand the impact of a form of randomness in a world where there is an active adversary.
