### ISSUE TITLE
please move implementations into declarations and git rid of ugly

### ISSUE THREAD

**Issue by happyjack27** [gburtini/Probability-Distributions-for-PHP#18]
please move implementations into declarations and git rid of ugly

**Comment by gburtini** [comment]
I tend to agree that it is time to end PHP 5.2 support, even if the only benefit is cleanliness in the repo. I will keep this issue open until it is done.

**Comment by gburtini** [comment]
Some data to support removing PHP 5.2 and not seriously worrying about 5.3 or 5.4 support: https://seld.be/notes/php-versions-stats-2017-1-edition

**Comment by gburtini** [comment]
@happyjack27 @mossadal - if someone wants to take charge on killing the ugly folder, this is the issue. It should be straightforward, fundamentally just relocating code and then changing the travis.yml to not run a 5.2 test. If not, I will try to get to it this weekend. Will be good to revisit this project for a few hours.

**Comment by mossadal** [comment]
I can have a go at this, but it'll probably take me a week or so.

**Comment by gburtini** [comment]
This will be done with the merger of https://github.com/gburtini/Probability-Distributions-for-PHP/pull/28
