### ISSUE TITLE
Code organization for new distributions?

### ISSUE THREAD

**Issue by mossadal** [gburtini/Probability-Distributions-for-PHP#20]
I intend to contribute a couple of additional distributions, Weibull, chi^2 and lognormal are highest on my list. 

Do you still think that the new code should support pre 5.3 with the ugly folder containing the actual implementation, or should I put the new code directly in the namespaced folder?

**Comment by happyjack27** [comment]
everything should be in the same spot.

where-ever you put it, put everything else there.

**Comment by gburtini** [comment]
I want to kill the ugly folder ASAP. Please do not waste your time building that implementation.

**Comment by gburtini** [comment]
I just see now that you have done it that way. That is also fine. It will get removed in #18 when we remove ugly.
