### ISSUE TITLE
Add versioning to the package

### ISSUE THREAD

**Issue by janklan** [gburtini/Probability-Distributions-for-PHP#27]
Hi, would it be possible to add versioning to the Composer package so that we can lock our code onto a specific version and be sure that no changes were made to the code we depend on between issuing individual `composer install` commands?

**Comment by gburtini** [comment]
Done. I just made two releases. 

One from the former current state (0.0.1), and one up-to-date with today's changes (0.0.2; no more PHP 5.3 support, linting everywhere, a bit of standardization, no API breaks/non-bug fixes that a user should notice).

https://github.com/gburtini/Probability-Distributions-for-PHP/tree/0.0.2

https://github.com/gburtini/Probability-Distributions-for-PHP/tree/0.0.1
