### ISSUE TITLE
BadMethodCallException: PDF not implemented. Please create a pull request if you implement it yourself. in /Library/WebServer/Documents/playground-raj/vendor/gburtini/distributions/src/gburtini/Distributions/Distribution.php on line 10

### ISSUE THREAD

**Issue by rajnandan1** [gburtini/Probability-Distributions-for-PHP#31]
![screenshot-localhost-2018 10 15-12-27-26](https://user-images.githubusercontent.com/16224367/46934549-c8001600-d075-11e8-8015-c98201e6ef40.png)

```
My COde

<?php
    include("./vendor/autoload.php");
    use gburtini\Distributions\Beta;
    $beta = new Beta(81, 219);
    $draw = $beta->rand();
    echo $draw;

    $beta->pdf(.9);
    // $beta->cdf($x) = [0,1] non-decreasing
    // $beta::quantile($y in [0,1]) = [0,1] (aliased Beta::icdf)
    // $beta->rand() = [0,1]
?>
```

**Comment by tvogt** [comment]
I'd love to have these functions available. If I understand correctly, it is possible to work around it by using gburtini\Distributions\Accessories\BetaFunction. I'm doing this to get a graph of the distribution curve to display it visually:

        $last = 0; $data = array();
        for ($i=0;$i<=1.0;$i+=0.01) {
            $b = BetaFunction::incompleteBetaFunction($i, $this->alpha, $this->beta);
            $data[] = $b-$last;
            $last = $b;
        }

**Comment by gustawdaniel** [comment]
For `beta` 

> https://en.wikipedia.org/wiki/Beta_distribution

CDF is definded by integral

> https://en.wikipedia.org/wiki/Beta_function#Incomplete_beta_function

Because of different needs we should balance between time and accuracy. I propose the following interface

```
$beta->cdf($x, ?$params) // optional $params as associative array with info about precision
```

**Comment by gustawdaniel** [comment]
@tvogt it looks good. I will test behavior of your solution tomorrow and type there about potential boundaries. I didn't know that this package has incompleteBetaFunction implemented.

**Comment by tvogt** [comment]
Look into Accessories\BetaFunction - there is quite a bit of code there which I mostly don't understand (I mean I understand the code, but not what it means).

**Comment by gustawdaniel** [comment]
@tvogt I added the following CDF for Beta Distribution.

```
    /**
     * @param $x
     * @return float|int
     * Definition: https://en.wikipedia.org/wiki/Beta_function#Incomplete_beta_function
     * we can calculate integral but better idea is to use fraction representation:
     * In our code there is implemented method http://functions.wolfram.com/GammaBetaErf/Beta3/10/
     */
    public function cdf($x)
    {
        return BetaFunction::incompleteBetaFunction($x, $this->alpha, $this->beta);
    }
```

In link

> http://functions.wolfram.com/GammaBetaErf/Beta3/10/

You have a representation of this function that has quite nice convergence. Integrating is more intuitive, but due to numerical reason is not preferred.
