### ISSUE TITLE
binomial icdf returns value > 1.0

### ISSUE THREAD

**Issue by dHellerstein** [gburtini/Probability-Distributions-for-PHP#38]
the binomial cdf prcduces a value greater than 1.0 when for N (the number of trials). If this is value is used in the icdf function, an error occurs. 

Example:
```php
 $bin1 = new Binomial(10,0.2);
 $cdf1=$bin1->cdf(10);
 $xxDo=$bin1->icdf($cdf1);
 print " For bin(10,0.2) : cdf(10) = $cdf1. Inverse of this= $xxDo";
```

 yields an error message:

```
 ( ! ) InvalidArgumentException: Parameter ($p = 1.0000000000000011 must  be between 0 and 1. in
```

**Comment by gburtini** [comment]
It probably isn't helpful to you nearly a year later, but I have fixed this [_specific_ issue](https://github.com/gburtini/Probability-Distributions-for-PHP/commit/8133d3a8666d7b7d1b463c5ebd54a87178ed7ed6). 

My fix truncates the result of the CDF function to be in the range [0, 1]. It does nothing to detect results that may be unreasonably outside that range (i.e., non-floating point errors). I added a test. 

I did not write the problematic code, but I believe the same bug exists in some form in the other distributions. While I was in there, I also noted there's some consistency issues between distributions (e.g., where some return INF, others return 1 or throw). I invite pull requests to fix any such issues or improve consistency anywhere.

I don't write PHP day-to-day anymore, so while I'm not necessarily _abandoning_ this library, I am not actively maintaining it either. I'll happily merge well-formed pull requests. There is a lot of cleanup this library would benefit from if someone wished to take over in any case.

**Comment by dHellerstein** [comment]
Hi GBurtini.

Since I had specific needs -- rapid generation of numerous RVs -- I extracted some of your code to create a "binomial only" set of functions.

They can be found at https://github.com/dHellerstein/wsurveyMath (https://github.com/dHellerstein/wsurveyMath/blob/main/binomialRvs.txt)

Thanks! 

Hmmm... I should  credit you in the readme (I do in the code). I will update! Do you have a preferred citation?
