### ISSUE TITLE
Student's T distribution buggy

### ISSUE THREAD

**Issue by mossadal** [gburtini/Probability-Distributions-for-PHP#6]
I worked through the next distribution on my list and found several issues with the implementation of StudentT.

The most serious being that `T::icdf` is returning values that are way off. For example

```
$T = new T(6);
echo $T->icdf(0.2)
```

gives `-4.8989794855663567` instead of the expected `-0.90570325863942802`.

Also, `T::pdf`doesn't reliably give an accuracy of better than `1e-5` or so, at least not for moderately large inputs. For example

```
$T = new T(6);
echo $T->pdf(-5)
```

returns `0.0012208409808473011` instead of `0.00122617088037926`.

I'll try to look into this today, but the likely culprit is the implementation of the beta, incomplete beta and inverse incomplete beta functions, and they don't look very appealing to dig through ;)

If I don't find a solution, I'll at least give you a PR with some tests.

**Comment by mossadal** [comment]
I found the bug, 

```
$x = GBPDP_BetaFunction::inverseIncompleteBetaFunction(2 * min($y, 1 - $y), 0.5 * $this->degrees, 0.5);
$x = sqrt($this->degrees * (1 - $y) / $y);   // Here is the bug!
return ($y > 0.5) ? $x : -$x;
```

I fixed it and replaced the implementation of `T::icdf` with something a little more numerically stable.

**Comment by mossadal** [comment]
I should have said that the issue of accuracy in `T::pdf` was due to a silly typo on my side.

**Comment by gburtini** [comment]
Dang. My undergrad. numerical methods professor would be very disappointed with me. :) - G.
