### ISSUE TITLE
Resolve licensing choices.

### ISSUE THREAD

**Issue by gburtini** [gburtini/Probability-Distributions-for-PHP#9]
This library is missing a clear license. I will want to clear any license choice with @mossadal and @graemedouglas as they have made significant contributions to the library without a clear license at this point. GPL or BSD/MIT should be considered.

The Cepheus library by which some of the code is derived is itself released under a very ambiguous license. This in some sense compromises the integrity of our own ability to relicense this library. https://lists.debian.org/debian-legal/2004/12/msg00295.html

**Comment by mossadal** [comment]
I agree that a clear license for the project would be welcome.

I am most certainly not a lawyer, but I'd be hesitant to use GPL for code of this type: a small library for more or less general use. BSD or MIT would be more suitable in my opinion and I don't have a strong preference for choosing between those two.

**Comment by gburtini** [comment]
We're all in agreement then. I spoke with Graeme via a different channel. I'll update the license appropriately.
